[colors.primary]
background = '#131313'
foreground = '#e2e2e2'

[colors.selection]
text = '#e2e2e2'
background = '#004d66'

[colors.cursor]
text = '#131313'
cursor = '#6ed2ff'

[colors.normal]
black   = '#131313'
red     = '#ff5f92'
green   = '#6eff7e'
yellow  = '#fff55f'
blue    = '#4cbef2'
magenta = '#005176'
cyan    = '#6ed2ff'
white   = '#edf9ff'

[colors.bright]
black   = '#97a1a5'
red     = '#ff92b5'
green   = '#99ffa4'
yellow  = '#fff899'
blue    = '#83d8ff'
magenta = '#99dfff'
cyan    = '#bdeaff'
white   = '#f7fcff'
