[colors.primary]
background = '#131313'
foreground = '#e2e2e2'

[colors.selection]
text = '#e2e2e2'
background = '#7a294d'

[colors.cursor]
text = '#131313'
cursor = '#ffb0cc'

[colors.normal]
black   = '#131313'
red     = '#ff7278'
green   = '#9fff7f'
yellow  = '#ffe172'
blue    = '#f298b8'
magenta = '#76324a'
cyan    = '#ffb0cc'
white   = '#ffeff5'

[colors.bright]
black   = '#a5999d'
red     = '#ff9fa3'
green   = '#bcffa5'
yellow  = '#ffeca5'
blue    = '#ffbbd3'
magenta = '#ffc7db'
cyan    = '#ffdbe8'
white   = '#fff8fa'
