decoration {
    rounding = 2
    # Change transparency of focused and unfocused windows
    active_opacity = 0.95
    inactive_opacity = 0.90
    dim_inactive = true
    dim_strength = 0.1
    dim_special = 0.40

    blur {
        enabled = true
        xray = false
        special = false
        # Allows opacity blurring
        ignore_opacity = true          
        new_optimizations = true
        popups = true
        input_methods = true
        size = 10
        passes = 5

        contrast = 0.85
        vibrancy = 1.8
        vibrancy_darkness = 0.15

    }

    shadow {
        enabled = false
         range = 6
         color = rgb($surfaceVariant)
         color_inactive = rgb($surfaceVariant)
    }
}

# REFERENCE
# https://wiki.hyprland.org/Configuring/Variables/#decoration
# decoration {
#     rounding = 2
#     # Change transparency of focused and unfocused windows
#     active_opacity = 0.90
#     inactive_opacity = 0.90
#     dim_inactive = true
#     dim_strength = 0.1
#     dim_special = 0.40
#     shadow {
#         enabled = true
#         range = 8
#         color = $color1
#         color_inactive = $color10
#
#     }
#     # https://wiki.hyprland.org/Configuring/Variables/#blur
#     blur {
#         enabled = true
#         size = 3
#         passes = 5
#         vibrancy = 0.1
#         new_optimizations = true
#         # special = true
#     }
# }
